name: Run tests

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.4.0
        with:
          mongodb-version: 4.4

      - run: cp .env.example .env

      - run: npm install

      - run: npm test
        env:
          CI: true
